on:
  workflow_dispatch:

name: Build

jobs:
  build:
    name: Build on NixOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Nix using channel 'nixpkgs-unstable'
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Build using Nix
        run: |
          nix-build --pure && ./result/bin/c2ffi --help && echo OK && cp ./result/bin/c2ffi /usr/local/bin/
      - uses: actions/upload-artifact@v3
        with:
          name: c2ffi
          path: /usr/local/bin/c2ffi
